name: Issue and Project Notification

on:
  issues:
    types: [opened, edited]
  project_card:
    types: [moved]
  issue_comment:
    types: [created, edited]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Notification: ${{ github.event_name }}"
          body: |
            ${{ if github.event_name == 'issues' }}
              A new issue has been created or updated in the repository:
              Issue Title: ${{ github.event.issue.title }}
              Issue Description: ${{ github.event.issue.body }}
              Issue URL: ${{ github.event.issue.html_url }}
            ${{ else if github.event_name == 'project_card' }}
              A card has been moved in the project:
              Card ID: ${{ github.event.project_card.id }}
              Card Note: ${{ github.event.project_card.note }}
              Card URL: ${{ github.event.project_card.url }}
            ${{ else if github.event_name == 'issue_comment' }}
              A comment has been created or edited in an issue:
              Issue Title: ${{ github.event.issue.title }}
              Comment Body: ${{ github.event.comment.body }}
              Comment URL: ${{ github.event.comment.html_url }}
            ${{ else }}
              Unexpected event: ${{ github.event_name }}
            ${{ endif }}
          to: alejandragarcia1@upb.edu
          from: aleandy7@gmail.com
